/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StudentAnalyticsRouteImport } from './routes/student-analytics'
import { Route as SkeletonPreviewRouteImport } from './routes/skeleton-preview'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as InsightBuddyRouteImport } from './routes/insight-buddy'
import { Route as HolisticReportsRouteImport } from './routes/holistic-reports'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as FlagsRouteImport } from './routes/flags'
import { Route as ErrorPreviewRouteImport } from './routes/error-preview'
import { Route as DsRouteImport } from './routes/ds'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AnnouncementsAdminRouteImport } from './routes/announcements-admin'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as MeetingsIndexRouteImport } from './routes/meetings.index'
import { Route as HolisticReportsIndexRouteImport } from './routes/holistic-reports.index'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as FormsIndexRouteImport } from './routes/forms.index'
import { Route as CalendarIndexRouteImport } from './routes/calendar.index'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements.index'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as ReportsTagRouteImport } from './routes/reports.tag'
import { Route as ReportsSummaryRouteImport } from './routes/reports.summary'
import { Route as ReportsReviewRouteImport } from './routes/reports.review'
import { Route as ReportsReleaseRouteImport } from './routes/reports.release'
import { Route as ReportsBroadcastRouteImport } from './routes/reports.broadcast'
import { Route as MeetingsNewRouteImport } from './routes/meetings.new'
import { Route as HolisticReportsIdRouteImport } from './routes/holistic-reports.$id'
import { Route as GroupsUploadRouteImport } from './routes/groups.upload'
import { Route as GroupsNewRouteImport } from './routes/groups.new'
import { Route as GroupsCreateRouteImport } from './routes/groups.create'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as GlowStudentIdRouteImport } from './routes/glow.$studentId'
import { Route as FormsNewRouteImport } from './routes/forms.new'
import { Route as FormsIdRouteImport } from './routes/forms.$id'
import { Route as AnnouncementsNewRouteImport } from './routes/announcements.new'
import { Route as AnnouncementsIdRouteImport } from './routes/announcements.$id'
import { Route as GuestStudentLoginRouteImport } from './routes/_guest.student-login'
import { Route as GuestPreviewMenuRouteImport } from './routes/_guest.preview-menu'
import { Route as GuestLoginRouteImport } from './routes/_guest.login'
import { Route as GuestCreateRouteImport } from './routes/_guest.create'
import { Route as ReportsStudentsIndexRouteImport } from './routes/reports.students.index'
import { Route as ReportsDraftsIndexRouteImport } from './routes/reports.drafts.index'
import { Route as ReportsStudentsStudentIdRouteImport } from './routes/reports.students.$studentId'
import { Route as ReportsDraftsStudentIdRouteImport } from './routes/reports.drafts.$studentId'
import { Route as GroupsStructuredGroupIdRouteImport } from './routes/groups.structured.$groupId'
import { Route as GuestHdpStudentTokenRouteImport } from './routes/_guest.hdp-student.$token'
import { Route as GuestHdpReportTokenRouteImport } from './routes/_guest.hdp-report.$token'
import { Route as StudentsIdAgencyReportNewRouteImport } from './routes/students_.$id.agency-report.new'

const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAnalyticsRoute = StudentAnalyticsRouteImport.update({
  id: '/student-analytics',
  path: '/student-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SkeletonPreviewRoute = SkeletonPreviewRouteImport.update({
  id: '/skeleton-preview',
  path: '/skeleton-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightBuddyRoute = InsightBuddyRouteImport.update({
  id: '/insight-buddy',
  path: '/insight-buddy',
  getParentRoute: () => rootRouteImport,
} as any)
const HolisticReportsRoute = HolisticReportsRouteImport.update({
  id: '/holistic-reports',
  path: '/holistic-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsRoute = FlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorPreviewRoute = ErrorPreviewRouteImport.update({
  id: '/error-preview',
  path: '/error-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DsRoute = DsRouteImport.update({
  id: '/ds',
  path: '/ds',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsAdminRoute = AnnouncementsAdminRouteImport.update({
  id: '/announcements-admin',
  path: '/announcements-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentsRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const MeetingsIndexRoute = MeetingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeetingsRoute,
} as any)
const HolisticReportsIndexRoute = HolisticReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HolisticReportsRoute,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsRoute,
} as any)
const FormsIndexRoute = FormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormsRoute,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CalendarRoute,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnnouncementsRoute,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentsRoute,
} as any)
const ReportsTagRoute = ReportsTagRouteImport.update({
  id: '/tag',
  path: '/tag',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsSummaryRoute = ReportsSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsReviewRoute = ReportsReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsReleaseRoute = ReportsReleaseRouteImport.update({
  id: '/release',
  path: '/release',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsBroadcastRoute = ReportsBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => ReportsRoute,
} as any)
const MeetingsNewRoute = MeetingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MeetingsRoute,
} as any)
const HolisticReportsIdRoute = HolisticReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HolisticReportsRoute,
} as any)
const GroupsUploadRoute = GroupsUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => GroupsRoute,
} as any)
const GroupsNewRoute = GroupsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => GroupsRoute,
} as any)
const GroupsCreateRoute = GroupsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => GroupsRoute,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => GroupsRoute,
} as any)
const GlowStudentIdRoute = GlowStudentIdRouteImport.update({
  id: '/glow/$studentId',
  path: '/glow/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsNewRoute = FormsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FormsRoute,
} as any)
const FormsIdRoute = FormsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FormsRoute,
} as any)
const AnnouncementsNewRoute = AnnouncementsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AnnouncementsRoute,
} as any)
const AnnouncementsIdRoute = AnnouncementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnnouncementsRoute,
} as any)
const GuestStudentLoginRoute = GuestStudentLoginRouteImport.update({
  id: '/student-login',
  path: '/student-login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestPreviewMenuRoute = GuestPreviewMenuRouteImport.update({
  id: '/preview-menu',
  path: '/preview-menu',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestCreateRoute = GuestCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => GuestRoute,
} as any)
const ReportsStudentsIndexRoute = ReportsStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsDraftsIndexRoute = ReportsDraftsIndexRouteImport.update({
  id: '/drafts/',
  path: '/drafts/',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsStudentsStudentIdRoute =
  ReportsStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => ReportsRoute,
  } as any)
const ReportsDraftsStudentIdRoute = ReportsDraftsStudentIdRouteImport.update({
  id: '/drafts/$studentId',
  path: '/drafts/$studentId',
  getParentRoute: () => ReportsRoute,
} as any)
const GroupsStructuredGroupIdRoute = GroupsStructuredGroupIdRouteImport.update({
  id: '/structured/$groupId',
  path: '/structured/$groupId',
  getParentRoute: () => GroupsRoute,
} as any)
const GuestHdpStudentTokenRoute = GuestHdpStudentTokenRouteImport.update({
  id: '/hdp-student/$token',
  path: '/hdp-student/$token',
  getParentRoute: () => GuestRoute,
} as any)
const GuestHdpReportTokenRoute = GuestHdpReportTokenRouteImport.update({
  id: '/hdp-report/$token',
  path: '/hdp-report/$token',
  getParentRoute: () => GuestRoute,
} as any)
const StudentsIdAgencyReportNewRoute =
  StudentsIdAgencyReportNewRouteImport.update({
    id: '/students_/$id/agency-report/new',
    path: '/students/$id/agency-report/new',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/announcements-admin': typeof AnnouncementsAdminRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRouteWithChildren
  '/ds': typeof DsRoute
  '/error-preview': typeof ErrorPreviewRoute
  '/flags': typeof FlagsRoute
  '/forms': typeof FormsRouteWithChildren
  '/groups': typeof GroupsRouteWithChildren
  '/holistic-reports': typeof HolisticReportsRouteWithChildren
  '/insight-buddy': typeof InsightBuddyRoute
  '/meetings': typeof MeetingsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skeleton-preview': typeof SkeletonPreviewRoute
  '/student-analytics': typeof StudentAnalyticsRoute
  '/students': typeof StudentsRouteWithChildren
  '/create': typeof GuestCreateRoute
  '/login': typeof GuestLoginRoute
  '/preview-menu': typeof GuestPreviewMenuRoute
  '/student-login': typeof GuestStudentLoginRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/announcements/new': typeof AnnouncementsNewRoute
  '/forms/$id': typeof FormsIdRoute
  '/forms/new': typeof FormsNewRoute
  '/glow/$studentId': typeof GlowStudentIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/new': typeof GroupsNewRoute
  '/groups/upload': typeof GroupsUploadRoute
  '/holistic-reports/$id': typeof HolisticReportsIdRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/reports/broadcast': typeof ReportsBroadcastRoute
  '/reports/release': typeof ReportsReleaseRoute
  '/reports/review': typeof ReportsReviewRoute
  '/reports/summary': typeof ReportsSummaryRoute
  '/reports/tag': typeof ReportsTagRoute
  '/students/$id': typeof StudentsIdRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/forms/': typeof FormsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/holistic-reports/': typeof HolisticReportsIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/hdp-report/$token': typeof GuestHdpReportTokenRoute
  '/hdp-student/$token': typeof GuestHdpStudentTokenRoute
  '/groups/structured/$groupId': typeof GroupsStructuredGroupIdRoute
  '/reports/drafts/$studentId': typeof ReportsDraftsStudentIdRoute
  '/reports/students/$studentId': typeof ReportsStudentsStudentIdRoute
  '/reports/drafts/': typeof ReportsDraftsIndexRoute
  '/reports/students/': typeof ReportsStudentsIndexRoute
  '/students/$id/agency-report/new': typeof StudentsIdAgencyReportNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/announcements-admin': typeof AnnouncementsAdminRoute
  '/attendance': typeof AttendanceRoute
  '/ds': typeof DsRoute
  '/error-preview': typeof ErrorPreviewRoute
  '/flags': typeof FlagsRoute
  '/insight-buddy': typeof InsightBuddyRoute
  '/settings': typeof SettingsRoute
  '/skeleton-preview': typeof SkeletonPreviewRoute
  '/student-analytics': typeof StudentAnalyticsRoute
  '/create': typeof GuestCreateRoute
  '/login': typeof GuestLoginRoute
  '/preview-menu': typeof GuestPreviewMenuRoute
  '/student-login': typeof GuestStudentLoginRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/announcements/new': typeof AnnouncementsNewRoute
  '/forms/$id': typeof FormsIdRoute
  '/forms/new': typeof FormsNewRoute
  '/glow/$studentId': typeof GlowStudentIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/new': typeof GroupsNewRoute
  '/groups/upload': typeof GroupsUploadRoute
  '/holistic-reports/$id': typeof HolisticReportsIdRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/reports/broadcast': typeof ReportsBroadcastRoute
  '/reports/release': typeof ReportsReleaseRoute
  '/reports/review': typeof ReportsReviewRoute
  '/reports/summary': typeof ReportsSummaryRoute
  '/reports/tag': typeof ReportsTagRoute
  '/students/$id': typeof StudentsIdRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/forms': typeof FormsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/holistic-reports': typeof HolisticReportsIndexRoute
  '/meetings': typeof MeetingsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/students': typeof StudentsIndexRoute
  '/hdp-report/$token': typeof GuestHdpReportTokenRoute
  '/hdp-student/$token': typeof GuestHdpStudentTokenRoute
  '/groups/structured/$groupId': typeof GroupsStructuredGroupIdRoute
  '/reports/drafts/$studentId': typeof ReportsDraftsStudentIdRoute
  '/reports/students/$studentId': typeof ReportsStudentsStudentIdRoute
  '/reports/drafts': typeof ReportsDraftsIndexRoute
  '/reports/students': typeof ReportsStudentsIndexRoute
  '/students/$id/agency-report/new': typeof StudentsIdAgencyReportNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_guest': typeof GuestRouteWithChildren
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/announcements-admin': typeof AnnouncementsAdminRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRouteWithChildren
  '/ds': typeof DsRoute
  '/error-preview': typeof ErrorPreviewRoute
  '/flags': typeof FlagsRoute
  '/forms': typeof FormsRouteWithChildren
  '/groups': typeof GroupsRouteWithChildren
  '/holistic-reports': typeof HolisticReportsRouteWithChildren
  '/insight-buddy': typeof InsightBuddyRoute
  '/meetings': typeof MeetingsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skeleton-preview': typeof SkeletonPreviewRoute
  '/student-analytics': typeof StudentAnalyticsRoute
  '/students': typeof StudentsRouteWithChildren
  '/_guest/create': typeof GuestCreateRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/preview-menu': typeof GuestPreviewMenuRoute
  '/_guest/student-login': typeof GuestStudentLoginRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/announcements/new': typeof AnnouncementsNewRoute
  '/forms/$id': typeof FormsIdRoute
  '/forms/new': typeof FormsNewRoute
  '/glow/$studentId': typeof GlowStudentIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/new': typeof GroupsNewRoute
  '/groups/upload': typeof GroupsUploadRoute
  '/holistic-reports/$id': typeof HolisticReportsIdRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/reports/broadcast': typeof ReportsBroadcastRoute
  '/reports/release': typeof ReportsReleaseRoute
  '/reports/review': typeof ReportsReviewRoute
  '/reports/summary': typeof ReportsSummaryRoute
  '/reports/tag': typeof ReportsTagRoute
  '/students/$id': typeof StudentsIdRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/forms/': typeof FormsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/holistic-reports/': typeof HolisticReportsIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/_guest/hdp-report/$token': typeof GuestHdpReportTokenRoute
  '/_guest/hdp-student/$token': typeof GuestHdpStudentTokenRoute
  '/groups/structured/$groupId': typeof GroupsStructuredGroupIdRoute
  '/reports/drafts/$studentId': typeof ReportsDraftsStudentIdRoute
  '/reports/students/$studentId': typeof ReportsStudentsStudentIdRoute
  '/reports/drafts/': typeof ReportsDraftsIndexRoute
  '/reports/students/': typeof ReportsStudentsIndexRoute
  '/students_/$id/agency-report/new': typeof StudentsIdAgencyReportNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/announcements'
    | '/announcements-admin'
    | '/attendance'
    | '/calendar'
    | '/ds'
    | '/error-preview'
    | '/flags'
    | '/forms'
    | '/groups'
    | '/holistic-reports'
    | '/insight-buddy'
    | '/meetings'
    | '/reports'
    | '/settings'
    | '/skeleton-preview'
    | '/student-analytics'
    | '/students'
    | '/create'
    | '/login'
    | '/preview-menu'
    | '/student-login'
    | '/announcements/$id'
    | '/announcements/new'
    | '/forms/$id'
    | '/forms/new'
    | '/glow/$studentId'
    | '/groups/$groupId'
    | '/groups/create'
    | '/groups/new'
    | '/groups/upload'
    | '/holistic-reports/$id'
    | '/meetings/new'
    | '/reports/broadcast'
    | '/reports/release'
    | '/reports/review'
    | '/reports/summary'
    | '/reports/tag'
    | '/students/$id'
    | '/announcements/'
    | '/calendar/'
    | '/forms/'
    | '/groups/'
    | '/holistic-reports/'
    | '/meetings/'
    | '/reports/'
    | '/students/'
    | '/hdp-report/$token'
    | '/hdp-student/$token'
    | '/groups/structured/$groupId'
    | '/reports/drafts/$studentId'
    | '/reports/students/$studentId'
    | '/reports/drafts/'
    | '/reports/students/'
    | '/students/$id/agency-report/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/announcements-admin'
    | '/attendance'
    | '/ds'
    | '/error-preview'
    | '/flags'
    | '/insight-buddy'
    | '/settings'
    | '/skeleton-preview'
    | '/student-analytics'
    | '/create'
    | '/login'
    | '/preview-menu'
    | '/student-login'
    | '/announcements/$id'
    | '/announcements/new'
    | '/forms/$id'
    | '/forms/new'
    | '/glow/$studentId'
    | '/groups/$groupId'
    | '/groups/create'
    | '/groups/new'
    | '/groups/upload'
    | '/holistic-reports/$id'
    | '/meetings/new'
    | '/reports/broadcast'
    | '/reports/release'
    | '/reports/review'
    | '/reports/summary'
    | '/reports/tag'
    | '/students/$id'
    | '/announcements'
    | '/calendar'
    | '/forms'
    | '/groups'
    | '/holistic-reports'
    | '/meetings'
    | '/reports'
    | '/students'
    | '/hdp-report/$token'
    | '/hdp-student/$token'
    | '/groups/structured/$groupId'
    | '/reports/drafts/$studentId'
    | '/reports/students/$studentId'
    | '/reports/drafts'
    | '/reports/students'
    | '/students/$id/agency-report/new'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_guest'
    | '/announcements'
    | '/announcements-admin'
    | '/attendance'
    | '/calendar'
    | '/ds'
    | '/error-preview'
    | '/flags'
    | '/forms'
    | '/groups'
    | '/holistic-reports'
    | '/insight-buddy'
    | '/meetings'
    | '/reports'
    | '/settings'
    | '/skeleton-preview'
    | '/student-analytics'
    | '/students'
    | '/_guest/create'
    | '/_guest/login'
    | '/_guest/preview-menu'
    | '/_guest/student-login'
    | '/announcements/$id'
    | '/announcements/new'
    | '/forms/$id'
    | '/forms/new'
    | '/glow/$studentId'
    | '/groups/$groupId'
    | '/groups/create'
    | '/groups/new'
    | '/groups/upload'
    | '/holistic-reports/$id'
    | '/meetings/new'
    | '/reports/broadcast'
    | '/reports/release'
    | '/reports/review'
    | '/reports/summary'
    | '/reports/tag'
    | '/students/$id'
    | '/announcements/'
    | '/calendar/'
    | '/forms/'
    | '/groups/'
    | '/holistic-reports/'
    | '/meetings/'
    | '/reports/'
    | '/students/'
    | '/_guest/hdp-report/$token'
    | '/_guest/hdp-student/$token'
    | '/groups/structured/$groupId'
    | '/reports/drafts/$studentId'
    | '/reports/students/$studentId'
    | '/reports/drafts/'
    | '/reports/students/'
    | '/students_/$id/agency-report/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  GuestRoute: typeof GuestRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRouteWithChildren
  AnnouncementsAdminRoute: typeof AnnouncementsAdminRoute
  AttendanceRoute: typeof AttendanceRoute
  CalendarRoute: typeof CalendarRouteWithChildren
  DsRoute: typeof DsRoute
  ErrorPreviewRoute: typeof ErrorPreviewRoute
  FlagsRoute: typeof FlagsRoute
  FormsRoute: typeof FormsRouteWithChildren
  GroupsRoute: typeof GroupsRouteWithChildren
  HolisticReportsRoute: typeof HolisticReportsRouteWithChildren
  InsightBuddyRoute: typeof InsightBuddyRoute
  MeetingsRoute: typeof MeetingsRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SkeletonPreviewRoute: typeof SkeletonPreviewRoute
  StudentAnalyticsRoute: typeof StudentAnalyticsRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  GlowStudentIdRoute: typeof GlowStudentIdRoute
  StudentsIdAgencyReportNewRoute: typeof StudentsIdAgencyReportNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-analytics': {
      id: '/student-analytics'
      path: '/student-analytics'
      fullPath: '/student-analytics'
      preLoaderRoute: typeof StudentAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skeleton-preview': {
      id: '/skeleton-preview'
      path: '/skeleton-preview'
      fullPath: '/skeleton-preview'
      preLoaderRoute: typeof SkeletonPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight-buddy': {
      id: '/insight-buddy'
      path: '/insight-buddy'
      fullPath: '/insight-buddy'
      preLoaderRoute: typeof InsightBuddyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holistic-reports': {
      id: '/holistic-reports'
      path: '/holistic-reports'
      fullPath: '/holistic-reports'
      preLoaderRoute: typeof HolisticReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags': {
      id: '/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof FlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-preview': {
      id: '/error-preview'
      path: '/error-preview'
      fullPath: '/error-preview'
      preLoaderRoute: typeof ErrorPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds': {
      id: '/ds'
      path: '/ds'
      fullPath: '/ds'
      preLoaderRoute: typeof DsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements-admin': {
      id: '/announcements-admin'
      path: '/announcements-admin'
      fullPath: '/announcements-admin'
      preLoaderRoute: typeof AnnouncementsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/meetings/': {
      id: '/meetings/'
      path: '/'
      fullPath: '/meetings/'
      preLoaderRoute: typeof MeetingsIndexRouteImport
      parentRoute: typeof MeetingsRoute
    }
    '/holistic-reports/': {
      id: '/holistic-reports/'
      path: '/'
      fullPath: '/holistic-reports/'
      preLoaderRoute: typeof HolisticReportsIndexRouteImport
      parentRoute: typeof HolisticReportsRoute
    }
    '/groups/': {
      id: '/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/forms/': {
      id: '/forms/'
      path: '/'
      fullPath: '/forms/'
      preLoaderRoute: typeof FormsIndexRouteImport
      parentRoute: typeof FormsRoute
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof CalendarRoute
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof AnnouncementsRoute
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/reports/tag': {
      id: '/reports/tag'
      path: '/tag'
      fullPath: '/reports/tag'
      preLoaderRoute: typeof ReportsTagRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/summary': {
      id: '/reports/summary'
      path: '/summary'
      fullPath: '/reports/summary'
      preLoaderRoute: typeof ReportsSummaryRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/review': {
      id: '/reports/review'
      path: '/review'
      fullPath: '/reports/review'
      preLoaderRoute: typeof ReportsReviewRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/release': {
      id: '/reports/release'
      path: '/release'
      fullPath: '/reports/release'
      preLoaderRoute: typeof ReportsReleaseRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/broadcast': {
      id: '/reports/broadcast'
      path: '/broadcast'
      fullPath: '/reports/broadcast'
      preLoaderRoute: typeof ReportsBroadcastRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/meetings/new': {
      id: '/meetings/new'
      path: '/new'
      fullPath: '/meetings/new'
      preLoaderRoute: typeof MeetingsNewRouteImport
      parentRoute: typeof MeetingsRoute
    }
    '/holistic-reports/$id': {
      id: '/holistic-reports/$id'
      path: '/$id'
      fullPath: '/holistic-reports/$id'
      preLoaderRoute: typeof HolisticReportsIdRouteImport
      parentRoute: typeof HolisticReportsRoute
    }
    '/groups/upload': {
      id: '/groups/upload'
      path: '/upload'
      fullPath: '/groups/upload'
      preLoaderRoute: typeof GroupsUploadRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/groups/new': {
      id: '/groups/new'
      path: '/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof GroupsNewRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/groups/create': {
      id: '/groups/create'
      path: '/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof GroupsCreateRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/glow/$studentId': {
      id: '/glow/$studentId'
      path: '/glow/$studentId'
      fullPath: '/glow/$studentId'
      preLoaderRoute: typeof GlowStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/new': {
      id: '/forms/new'
      path: '/new'
      fullPath: '/forms/new'
      preLoaderRoute: typeof FormsNewRouteImport
      parentRoute: typeof FormsRoute
    }
    '/forms/$id': {
      id: '/forms/$id'
      path: '/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof FormsIdRouteImport
      parentRoute: typeof FormsRoute
    }
    '/announcements/new': {
      id: '/announcements/new'
      path: '/new'
      fullPath: '/announcements/new'
      preLoaderRoute: typeof AnnouncementsNewRouteImport
      parentRoute: typeof AnnouncementsRoute
    }
    '/announcements/$id': {
      id: '/announcements/$id'
      path: '/$id'
      fullPath: '/announcements/$id'
      preLoaderRoute: typeof AnnouncementsIdRouteImport
      parentRoute: typeof AnnouncementsRoute
    }
    '/_guest/student-login': {
      id: '/_guest/student-login'
      path: '/student-login'
      fullPath: '/student-login'
      preLoaderRoute: typeof GuestStudentLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/preview-menu': {
      id: '/_guest/preview-menu'
      path: '/preview-menu'
      fullPath: '/preview-menu'
      preLoaderRoute: typeof GuestPreviewMenuRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/create': {
      id: '/_guest/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof GuestCreateRouteImport
      parentRoute: typeof GuestRoute
    }
    '/reports/students/': {
      id: '/reports/students/'
      path: '/students'
      fullPath: '/reports/students/'
      preLoaderRoute: typeof ReportsStudentsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/drafts/': {
      id: '/reports/drafts/'
      path: '/drafts'
      fullPath: '/reports/drafts/'
      preLoaderRoute: typeof ReportsDraftsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/students/$studentId': {
      id: '/reports/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/reports/students/$studentId'
      preLoaderRoute: typeof ReportsStudentsStudentIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/drafts/$studentId': {
      id: '/reports/drafts/$studentId'
      path: '/drafts/$studentId'
      fullPath: '/reports/drafts/$studentId'
      preLoaderRoute: typeof ReportsDraftsStudentIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/groups/structured/$groupId': {
      id: '/groups/structured/$groupId'
      path: '/structured/$groupId'
      fullPath: '/groups/structured/$groupId'
      preLoaderRoute: typeof GroupsStructuredGroupIdRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/_guest/hdp-student/$token': {
      id: '/_guest/hdp-student/$token'
      path: '/hdp-student/$token'
      fullPath: '/hdp-student/$token'
      preLoaderRoute: typeof GuestHdpStudentTokenRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/hdp-report/$token': {
      id: '/_guest/hdp-report/$token'
      path: '/hdp-report/$token'
      fullPath: '/hdp-report/$token'
      preLoaderRoute: typeof GuestHdpReportTokenRouteImport
      parentRoute: typeof GuestRoute
    }
    '/students_/$id/agency-report/new': {
      id: '/students_/$id/agency-report/new'
      path: '/students/$id/agency-report/new'
      fullPath: '/students/$id/agency-report/new'
      preLoaderRoute: typeof StudentsIdAgencyReportNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuestRouteChildren {
  GuestCreateRoute: typeof GuestCreateRoute
  GuestLoginRoute: typeof GuestLoginRoute
  GuestPreviewMenuRoute: typeof GuestPreviewMenuRoute
  GuestStudentLoginRoute: typeof GuestStudentLoginRoute
  GuestHdpReportTokenRoute: typeof GuestHdpReportTokenRoute
  GuestHdpStudentTokenRoute: typeof GuestHdpStudentTokenRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestCreateRoute: GuestCreateRoute,
  GuestLoginRoute: GuestLoginRoute,
  GuestPreviewMenuRoute: GuestPreviewMenuRoute,
  GuestStudentLoginRoute: GuestStudentLoginRoute,
  GuestHdpReportTokenRoute: GuestHdpReportTokenRoute,
  GuestHdpStudentTokenRoute: GuestHdpStudentTokenRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface AnnouncementsRouteChildren {
  AnnouncementsIdRoute: typeof AnnouncementsIdRoute
  AnnouncementsNewRoute: typeof AnnouncementsNewRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
}

const AnnouncementsRouteChildren: AnnouncementsRouteChildren = {
  AnnouncementsIdRoute: AnnouncementsIdRoute,
  AnnouncementsNewRoute: AnnouncementsNewRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
}

const AnnouncementsRouteWithChildren = AnnouncementsRoute._addFileChildren(
  AnnouncementsRouteChildren,
)

interface CalendarRouteChildren {
  CalendarIndexRoute: typeof CalendarIndexRoute
}

const CalendarRouteChildren: CalendarRouteChildren = {
  CalendarIndexRoute: CalendarIndexRoute,
}

const CalendarRouteWithChildren = CalendarRoute._addFileChildren(
  CalendarRouteChildren,
)

interface FormsRouteChildren {
  FormsIdRoute: typeof FormsIdRoute
  FormsNewRoute: typeof FormsNewRoute
  FormsIndexRoute: typeof FormsIndexRoute
}

const FormsRouteChildren: FormsRouteChildren = {
  FormsIdRoute: FormsIdRoute,
  FormsNewRoute: FormsNewRoute,
  FormsIndexRoute: FormsIndexRoute,
}

const FormsRouteWithChildren = FormsRoute._addFileChildren(FormsRouteChildren)

interface GroupsRouteChildren {
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsCreateRoute: typeof GroupsCreateRoute
  GroupsNewRoute: typeof GroupsNewRoute
  GroupsUploadRoute: typeof GroupsUploadRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  GroupsStructuredGroupIdRoute: typeof GroupsStructuredGroupIdRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsCreateRoute: GroupsCreateRoute,
  GroupsNewRoute: GroupsNewRoute,
  GroupsUploadRoute: GroupsUploadRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  GroupsStructuredGroupIdRoute: GroupsStructuredGroupIdRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

interface HolisticReportsRouteChildren {
  HolisticReportsIdRoute: typeof HolisticReportsIdRoute
  HolisticReportsIndexRoute: typeof HolisticReportsIndexRoute
}

const HolisticReportsRouteChildren: HolisticReportsRouteChildren = {
  HolisticReportsIdRoute: HolisticReportsIdRoute,
  HolisticReportsIndexRoute: HolisticReportsIndexRoute,
}

const HolisticReportsRouteWithChildren = HolisticReportsRoute._addFileChildren(
  HolisticReportsRouteChildren,
)

interface MeetingsRouteChildren {
  MeetingsNewRoute: typeof MeetingsNewRoute
  MeetingsIndexRoute: typeof MeetingsIndexRoute
}

const MeetingsRouteChildren: MeetingsRouteChildren = {
  MeetingsNewRoute: MeetingsNewRoute,
  MeetingsIndexRoute: MeetingsIndexRoute,
}

const MeetingsRouteWithChildren = MeetingsRoute._addFileChildren(
  MeetingsRouteChildren,
)

interface ReportsRouteChildren {
  ReportsBroadcastRoute: typeof ReportsBroadcastRoute
  ReportsReleaseRoute: typeof ReportsReleaseRoute
  ReportsReviewRoute: typeof ReportsReviewRoute
  ReportsSummaryRoute: typeof ReportsSummaryRoute
  ReportsTagRoute: typeof ReportsTagRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  ReportsDraftsStudentIdRoute: typeof ReportsDraftsStudentIdRoute
  ReportsStudentsStudentIdRoute: typeof ReportsStudentsStudentIdRoute
  ReportsDraftsIndexRoute: typeof ReportsDraftsIndexRoute
  ReportsStudentsIndexRoute: typeof ReportsStudentsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsBroadcastRoute: ReportsBroadcastRoute,
  ReportsReleaseRoute: ReportsReleaseRoute,
  ReportsReviewRoute: ReportsReviewRoute,
  ReportsSummaryRoute: ReportsSummaryRoute,
  ReportsTagRoute: ReportsTagRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  ReportsDraftsStudentIdRoute: ReportsDraftsStudentIdRoute,
  ReportsStudentsStudentIdRoute: ReportsStudentsStudentIdRoute,
  ReportsDraftsIndexRoute: ReportsDraftsIndexRoute,
  ReportsStudentsIndexRoute: ReportsStudentsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface StudentsRouteChildren {
  StudentsIdRoute: typeof StudentsIdRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsIdRoute: StudentsIdRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  GuestRoute: GuestRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRouteWithChildren,
  AnnouncementsAdminRoute: AnnouncementsAdminRoute,
  AttendanceRoute: AttendanceRoute,
  CalendarRoute: CalendarRouteWithChildren,
  DsRoute: DsRoute,
  ErrorPreviewRoute: ErrorPreviewRoute,
  FlagsRoute: FlagsRoute,
  FormsRoute: FormsRouteWithChildren,
  GroupsRoute: GroupsRouteWithChildren,
  HolisticReportsRoute: HolisticReportsRouteWithChildren,
  InsightBuddyRoute: InsightBuddyRoute,
  MeetingsRoute: MeetingsRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SkeletonPreviewRoute: SkeletonPreviewRoute,
  StudentAnalyticsRoute: StudentAnalyticsRoute,
  StudentsRoute: StudentsRouteWithChildren,
  GlowStudentIdRoute: GlowStudentIdRoute,
  StudentsIdAgencyReportNewRoute: StudentsIdAgencyReportNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
